extends: ./node_modules/@telenorfrontend/tn-conventions/scss/.stylelintrc.yml
rules:
  selector-max-type: 2
  at-rule-no-unknown:
  - true
  - ignoreAtRules:
    - 'include'
    - 'mixin'
    - 'if'
    - 'else'
    - 'content'
